### ISSUE TITLE
Cloudwatch logs

### ISSUE THREAD

**Issue by fvthree** [yosriady/serverless-crud-go#2]
Hi bro,

I was returned this json when I curl  the hello endpoint:

{
    "message": "Internal server error"
}

When I check the Cloudwatch logs this is the message:

fork/exec /var/task/bin/handlers/hello: permission denied: PathError null

**Comment by yosriady** [comment]
Can you check your lambda .zip deployment package to see if the handlers
are built correctly? If you run the build scripts and follow the steps in
the README it should be working.

**Comment by fvthree** [comment]
yup i tried checking it. it contains something like a 4mb for addTodo file and 2mb for hello. I've read this problem occur because I'm using windows to zip file

**Comment by yosriady** [comment]
Can you try using another .zip program like 7zip?

I know that there are some issues with zipping AWS Lambda deployment
packages with Powershell: https://github.com/apex/apex/issues/596

**Comment by fvthree** [comment]
Yeah that seems easy. 
I wonder how I will deploy it using the sls deploy -v command together with the zip files?

**Comment by yosriady** [comment]
You can tell the Serverless framework that you have your own .zip file:
https://serverless.com/framework/docs/providers/aws/guide/packaging#artifact

The .zip file would contain the contents of the `/bin` folder generated from `/scripts/build.sh/`.

**Comment by fvthree** [comment]
Still the same error.

Now I can't find my zip files in s3 after changing the serverless.yml into: 

```
functions:
  hello:
    handler: bin/handlers/hello
    package:
      artifact: ./bin/handlers/hello.zip
    events:
      - http:
          path: hello
          method: get
          cors: true
  addTodo:
    handler: bin/handlers/addTodo
    package:
      artifact: ./bin/handlers/addTodo.zip
    events:
      - http:
          path: todos
          method: post
          cors: true
```
